DROP TABLE dyno CASCADE;
DROP TABLE human CASCADE;
DROP TABLE wound CASCADE;
DROP TABLE body CASCADE;

DROP TABLE wound_to_body CASCADE;
DROP TABLE dyno_to_human CASCADE;
DROP TABLE body_to_human CASCADE ;

DROP TABLE position CASCADE;